[package]
name = "nakamoto"
readme = "README.md"
license = "MIT"
version = "0.1.0"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2018"

[workspace]
members = [
  "nakamoto-p2p",
  "nakamoto-chain",
  "nakamoto-node",
  "nakamoto-test",
  "nakamoto-daemon",
]

[dependencies]
nakamoto-node = { path = "./nakamoto-node", optional = true }
nakamoto-daemon = { path = "./nakamoto-daemon", optional = true }
nakamoto-chain = { path = "./nakamoto-chain", optional = true }
nakamoto-p2p = { path = "./nakamoto-p2p", optional = true }
nakamoto-test = { path = "./nakamoto-test", optional = true }
