[package]
name = "nakamoto-common"
description = "Common types and functions shared by all nakamoto crates"
repository = "https://github.com/cloudhead/nakamoto"
license = "MIT"
version = "0.1.0"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2018"

[dependencies]
bitcoin = "0.23"
bitcoin_hashes = "0.7.6"
thiserror = "1.0"
fastrand = "1.3.4"
log = { version = "0.4", optional = true }
